# Generated by Django 2.2.6 on 2020-03-31 04:10

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User
import os



class Migration(migrations.Migration):

    u = User(username="mnour")
    u.set_password("mnour123")
    u.is_superuser = True
    u.is_staff = True
    try:
        u.save()
    except Exception:
        pass
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('benutzer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('anmeldename', models.CharField(blank=True, default='', max_length=256)),
                ('password', models.CharField(blank=True, default='', max_length=256)),
                ('telefonnr', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'benutzer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hersteller',
            fields=[
                ('hersteller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'hersteller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(blank=True, default='', max_length=256)),
                ('serverschrank', models.PositiveIntegerField(default=1)),
                ('max_temp', models.PositiveIntegerField(default=1)),
                ('hersteller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.Hersteller')),
            ],
            options={
                'db_table': 'sensors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Temperaturen',
            fields=[
                ('temperatur_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(auto_now=True, help_text='Update Date')),
                ('temperatur', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.Sensors')),
            ],
            options={
                'db_table': 'temperaturen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateTimeField(auto_now=True, help_text='Update Date')),
                ('nachricht', models.CharField(blank=True, default='', max_length=256)),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.Benutzer')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.Sensors')),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
