# Generated by Django 2.2.6 on 2020-03-31 05:21


from __future__ import unicode_literals
from django.db import models, migrations

def load_stores_from_sql():
    import os
    PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
    sql_statements = open(os.path.join(PROJECT_DIR,'../../seed.sql'), 'r').read()
    return sql_statements


class Migration(migrations.Migration):



    dependencies = [
        ('App','0001_initial')
    ]   

    operations = [
        migrations.RunSQL(load_stores_from_sql())
    ]